
OrdererOrgs:
 
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
   
  - Name: Org 1
    Domain: Org 1.com
    CA:
       Hostname: ca.Org 1.com  
    Template:
      Count: 2
    SANS:
        - "localhost"
    Users:
      Count: 1
 
  - Name: Org 1
    Domain: Org 1.com
    CA:
       Hostname: ca.Org 1.com  
    Template:
      Count: 2
    SANS:
        - "localhost"
    Users:
      Count: 1
 
  - Name: Org 2
    Domain: Org 2.com
    CA:
       Hostname: ca.Org 2.com  
    Template:
      Count: 2
    SANS:
        - "localhost"
    Users:
      Count: 1
 
  - Name: Org 2
    Domain: Org 2.com
    CA:
       Hostname: ca.Org 2.com  
    Template:
      Count: 2
    SANS:
        - "localhost"
    Users:
      Count: 1
