
OrdererOrgs:
 
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
   
  - Name: mdçwamdç
    Domain: mdçwamdç.com
    CA:
       Hostname: ca.mdçwamdç.com  
    Template:
      Count: 1
    SANS:
        - "localhost"
    Users:
      Count: 1
 
  - Name: mdçwamdç
    Domain: mdçwamdç.com
    CA:
       Hostname: ca.mdçwamdç.com  
    Template:
      Count: 2
    SANS:
        - "localhost"
    Users:
      Count: 1
 
  - Name: dawda
    Domain: dawda.com
    CA:
       Hostname: ca.dawda.com  
    Template:
      Count: 1
    SANS:
        - "localhost"
    Users:
      Count: 1
 
  - Name: dawda
    Domain: dawda.com
    CA:
       Hostname: ca.dawda.com  
    Template:
      Count: 2
    SANS:
        - "localhost"
    Users:
      Count: 1
