
OrdererOrgs:
 
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
   
  - Name: org1
    Domain: org1.com
    CA:
       Hostname: ca.org1.com  
    Template:
      Count: 2
    SANS:
        - "localhost"
    Users:
      Count: 1
 
  - Name: org2
    Domain: org2.com
    CA:
       Hostname: ca.org2.com  
    Template:
      Count: 2
    SANS:
        - "localhost"
    Users:
      Count: 1
