
OrdererOrgs:
 
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
   
  - Name: org
    Domain: org.com
    CA:
       Hostname: ca.org.com  
    Template:
      Count: 2
    SANS:
        - "localhost"
    Users:
      Count: 1
 
  - Name: safe
    Domain: safe.com
    CA:
       Hostname: ca.safe.com  
    Template:
      Count: 2
    SANS:
        - "localhost"
    Users:
      Count: 1
